### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by ahertlcode** [silverqx/TinyORM#12]
/home/abayomi/TinyORM/tom/src/tom/commands/migrations/statuscommand.cpp: In lambda function:
/home/abayomi/TinyORM/tom/src/tom/commands/migrations/statuscommand.cpp:78:22: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘const TableRow&’ {aka ‘const std::vector<std::vector<std::variant<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, const char*, std::basic_string_view<char, std::char_traits<char> >, tabulate::Table> > >&’}
   78 |                 table({"Ran?", "Migration", "Batch"}, migrations);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/TinyOrm.dir/build.make:1613: CMakeFiles/TinyOrm.dir/tom/src/tom/commands/migrations/statuscommand.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/TinyOrm.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I run into the error above while compiling TinyORM on my Ubuntu 22.04 machine. 
I pull the code from the repo with:
`git clone https://github.com/silverqx/TinyORM.git`
then i cd into the project directory
`cd TinyORM`
then I made and cd into buidl directory
`mkdir build && cd build`
I ran the cmake command which was successful i.e. it did not return any error
`cmake ..`
After which I then ran the make command
`make`
And I got the error above at exactly 85%

**Comment by silverqx** [comment]
Hi, which version of the **tabulate** do you have?

**Comment by ahertlcode** [comment]
tabulate version  is 1.5, what version would work perfectly.

**Comment by silverqx** [comment]
Ok, I see it, I'm going to fix it.

> what version would work perfectly.

Use v1.4 or v1.3 for now.

**Comment by ahertlcode** [comment]
Alright. Thanks

**Comment by silverqx** [comment]
Currently are running [CI](https://github.com/silverqx/TinyORM/actions) pipelines, when they finish (~1.5 hour) I will push a new release that will also work with tabulate v1.5.

**Comment by silverqx** [comment]
For me also the tabulate v1.3 works, if I do `git switch v1.3 --detach` then it compiles.

**Comment by ahertlcode** [comment]
Alright
