### ISSUE TITLE
Is there an interface to create tables?

### ISSUE THREAD

**Issue by zynfly** [silverqx/TinyORM#2]
can generate table creation statements or generate new data tables directly from the model

**Comment by silverqx** [comment]
No, the query builder or model doesn't have any DDL-related methods. And also any migrations for now. 

Database tables for tests are generated with PHP script [here](https://github.com/silverqx/TinyORM/blob/main/tests/testdata/create_and_seed_database.php) by help with Laravel's Schema builder.

**Comment by silverqx** [comment]
I'm personally creating tables with phpmyadmin or with Laravel schema builder for my personal usage, but would be amazing to have also schema builder in TinyOrm.

**Comment by zynfly** [comment]
Can I use TinyOrm to execute my own table creation statement?

**Comment by zynfly** [comment]
TinyOrm looks like a great library. I tried it for the first time today. Now I don't know how to use it to create tables.

**Comment by silverqx** [comment]
Yes, you can use [`DB::statement()`](https://github.com/silverqx/TinyORM/blob/main/include/orm/db.hpp#L117) or [`DB::unprepared()`](https://github.com/silverqx/TinyORM/blob/main/include/orm/db.hpp#L123).

**Comment by zynfly** [comment]
Thanks! The table has been created.

**Comment by silverqx** [comment]
I have added [`Schema builder`](https://www.tinyorm.org/schema-builder) for MySQL db, only one thing that is not implemented is updating database columns. 😁😎 @zynfly

**Comment by zynfly** [comment]
I'll try it now. It looks very cool.

**Comment by silverqx** [comment]
I have released `tom` migrations; [commit](https://github.com/silverqx/TinyORM/commit/a6213a6a9d3290fe4e70ead41d387fadc8426438), here are [docs](https://www.tinyorm.org/migrations) and how to build [docs](https://www.tinyorm.org/building-migrations). @zynfly 

I think that it'S all I will add related to the `DDL`, maybe the seeder in the future 😎.

Here are some images how the `tom` migrations looks like:

![tom_list](https://user-images.githubusercontent.com/86900/167166907-b71fdce0-060e-4643-a66f-8225c4f4eb5d.png)

![tom_migrate_rollback_inspire](https://user-images.githubusercontent.com/86900/167166933-bb691e2b-8db3-40e2-bc9f-acfafb0c3c86.png)

![tom_migrate_status_1](https://user-images.githubusercontent.com/86900/167167522-b01ce67c-98b3-4e88-9948-e1e3016c132d.png)

Happy migrating 🎉👌

**Comment by zynfly** [comment]
This is really great. It has become more and more perfect.
