### ISSUE TITLE
Assertive TinyOrmConfig.cmake breaks static builds

### ISSUE THREAD

**Issue by SchaichAlonso** [silverqx/TinyORM#21]
When searching for a TinyORM installation via `find_package(TinyORM)`, the `TinyORMConfig.cmake` script generated from [cmake/TinyOrmConfig.cmake.in](https://github.com/silverqx/TinyORM/blob/d98ee5c6c5e535ef657a46e632e7c9fc4b48851e/cmake/TinyOrmConfig.cmake.in) will assert on the existance of `${TinyORM_ROOT}/bin` in [line 21 of it's source script](https://github.com/silverqx/TinyORM/blob/d98ee5c6c5e535ef657a46e632e7c9fc4b48851e/cmake/TinyOrmConfig.cmake.in#L21) and store the result into a variable that isn't referenced by the find_package logic.

If a static-only TinyORM is installed, the corresponding path will not be created during installation as the static library resides in `lib` rather then `bin`, causing `find_package` invokations by consuming projects to fail.

**Comment by silverqx** [comment]
I want to ask, are these static builds working? I don't mean installation but if you can execute it correctly and on what OS are you building?

**Comment by SchaichAlonso** [comment]
I'm not sure about TinyORM's primary ORM capabilities, but the querybuilder works in static linkage mode... on Debian, Manjaro, and FreeBSD.

I'll try Windows later

**Comment by silverqx** [comment]
Great to hear, the querybuilder is most important. The ORM is header only so that should be ok too but in C++ anything can happen.

**Comment by SchaichAlonso** [comment]
static builds of TinyORM work on windows, too (requires #18 though, as a linker warning breaks the build due to `/WX`)

**Comment by silverqx** [comment]
I have tried CMake static build with Qt6 msvc now and I was successful, no fails.

**Comment by silverqx** [comment]
Tried with BUILD_SHARED_LIBS=OFF, TOM_EXAMPLE=ON, BUILD_TESTS=ON, MYSQL_PING=ON, also all tests passed so this should be ok.

**Comment by SchaichAlonso** [comment]
> I have tried CMake static build with Qt6 msvc now and I was successful, no fails.

I'm not getting any warnings on my workstation either, however I'm seeing them [occur on the github runners](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/actions/runs/5919340830/job/16049529304#step:8:2819). 

Appearently the warnings are gone on github, too, after updating TinyORM from 0.33.0 to 0.34.0 .

**Comment by silverqx** [comment]
Thank you, merged, also pls merge `PR`-s to the `develop` branch rather than the `main` branch.
