### ISSUE TITLE
VCPKG misplaces debug target export file

### ISSUE THREAD

**Issue by SchaichAlonso** [silverqx/TinyORM#25]
VCPKG uses [cmake/vcpkg/ports/tinyorm/cmake/tiny_cmake_config_fixup.cmake](https://github.com/silverqx/TinyORM/blob/d98ee5c6c5e535ef657a46e632e7c9fc4b48851e/cmake/vcpkg/ports/tinyorm/cmake/tiny_cmake_config_fixup.cmake) to "move" the debug target file into another directory.

Assuming the [${TinyOrm_ns}](https://github.com/silverqx/TinyORM/blob/d98ee5c6c5e535ef657a46e632e7c9fc4b48851e/cmake/vcpkg/ports/tinyorm/cmake/tiny_cmake_config_fixup.cmake#L8) is the subdirectory containing targets, the release file will also be in `${TinyOrm_ns}` rather then [${PORT}](https://github.com/silverqx/TinyORM/blob/d98ee5c6c5e535ef657a46e632e7c9fc4b48851e/cmake/vcpkg/ports/tinyorm/cmake/tiny_cmake_config_fixup.cmake#L9), unless `${PORT}` happens to be identical to `${TinyOrm_ns}`, but even then only one of those names should be used for simplicity.

`${PORT}` will expand to `tinyorm`, while `${TinyOrm_ns}` expands to `TinyOrm`. On filesystems that support uppercase characters to be differenciated from lowercase characters (or any other variations), this causes the debug target export file to reside in a different path then the release export file:

    vcpkg/packages/tinyorm_x64-linux/share/cmake
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm/TinyOrmTargets.cmake
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm/Modules
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm/Modules/TinyPackageConfigHelpers.cmake
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm/TinyOrmConfig.cmake
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm/TinyOrmConfigVersion.cmake
    vcpkg/packages/tinyorm_x64-linux/share/cmake/TinyOrm/TinyOrmTargets-release.cmake
    vcpkg/packages/tinyorm_x64-linux/share/cmake/tinyorm
    vcpkg/packages/tinyorm_x64-linux/share/cmake/tinyorm/TinyOrmTargets-debug.cmake

**Comment by silverqx** [comment]
Nice catch

**Comment by silverqx** [comment]
Thx merged 👍
