### ISSUE TITLE
[cmake] Installing mdx documentation

### ISSUE THREAD

**Issue by silverqx** [silverqx/TinyORM#32]
TInyORM use Docusaurus for documentation so all files in the `docs/` folder are `*.mdx` files, what means they also contain javascript, or they contain also images which are in the `assets/` folders.

Should I install this type of documentation with CMake? Should be installed also in `vcpkg` port?

**Comment by silverqx** [comment]
@SchaichAlonso

**Comment by silverqx** [comment]
Here is the link to the related [source code](https://github.com/silverqx/TinyORM/blob/main/cmake/Modules/TinyDeployment.cmake#L52).

Also, this command is buggy because it isn't recursive, it installs only depth 1.

**Comment by silverqx** [comment]
It should look something like this:

```
install(DIRECTORY "docs/" DESTINATION "${CMAKE_INSTALL_DOCDIR}/mdx")
```

The question is whether I should actually install them.

**Comment by silverqx** [comment]
I think it's totally fine to not install these `mdx` docs in vcpkg, it's good for now and I leave it for later for solving or future enhancements.

**Comment by SchaichAlonso** [comment]
> Do you know any vcpkg package that is installing docs? md or man page docs, I want to look for inspiration, I didn't find any but I only spent a few minutes on this.

[opengl-registry](https://github.com/microsoft/vcpkg/blob/d5b03c125afee1d9cef38f4cfa77e229400fb48a/ports/opengl-registry) installs documentation into `share/opengl`
