### ISSUE TITLE
Many-to-many and wrong detach() overload?

### ISSUE THREAD

**Issue by silverqx** [silverqx/TinyORM#42]
Hi. I don't think I should open an issue because of this because maybe I'm doing something wrong. But i have a small confusion with Many To Many Relationships. I set everything up according to the documentation and then I had to delete Many To Many relationships. I found it in the documentation and there is an example.
```
// Detach a single role from the user...
user->roles()->detach(roleId);

// Detach all roles from the user...
user->roles()->detach();
```
But when I tried to make the same in my code
```
int32_t song_id = std::stoi(pkeysData[1]);
	artist->songs()->detach(song_id);
```
The wrong overload of detach function is called. I started debugging and this function was called 
```
template<class Model, class Related, class PivotType>
int
InteractsWithPivotTable<Model, Related, PivotType>::detach(const bool touch) const
{
    return detach(true, {}, touch);
}
```
So I provided a second argument
```
artist->songs()->detach(song_id, false);
```
and then a correct overload of function was called
```
    template<class Model, class Related, class PivotType>
    int InteractsWithPivotTable<Model, Related, PivotType>::detach(
            const QVariant &id, const bool touch) const
    {
        return detach(QVector<QVariant> {id}, touch);
    }
```
I'm wondering if I'm doing something wrong or if it's a bug in the documentation? By @SkaLe3

**Comment by silverqx** [comment]
thx for reporting, I need to check it @SkaLe3

**Comment by silverqx** [comment]
It selects that `detach(bool touch = true)` overload this is normal, it's c++ thing, I will have to figure out something about this, maybe rename it to `detachAll(bool touch = true)` or something.

For now, the best thing you can do is call like `artist->songs()->detach(QVariant(song_id), false);`.

**Comment by SkaLe3** [comment]
That makes sense, thank you!

**Comment by silverqx** [comment]
This is the reason why it is happening [Boolean conversions](https://en.cppreference.com/w/cpp/language/implicit_conversion#Boolean_conversions)

**Comment by silverqx** [comment]
I renamed it to `detachAll(bool)` [here](https://github.com/silverqx/TinyORM/commit/953dad6d57bcec98591231c5364d9111a3aedac2) and also added some functional tests [here](https://github.com/silverqx/TinyORM/commit/0d6d1fdb1bee096ef79b80ac03104d1758d36af0). I also merged it into the main branch.
