### ISSUE TITLE
Model implementing belongsToMany not compiling

### ISSUE THREAD

**Issue by Redmanacac** [silverqx/TinyORM#43]
The _Model Structure_ example provided in https://www.tinyorm.org/tinyorm/relationships#many-to-many does not compile.

`..hasrelationships.hpp:561: error: C2679: binary '=': no operator found which takes a right-hand operand of type 'std::optional<Derived>' (or there is no acceptable conversion)`
The example you provided was not that easy to compile for me because of some dependencies. I copied the model classes into my project and still get the same error as stated above.

**Comment by silverqx** [comment]
If I don't see an exact example code I can't tell where the problem can be.

**Comment by Redmanacac** [comment]
```
#pragma once
#ifndef MODELS_USER_HPP
#define MODELS_USER_HPP

#include <QStringList>

#include <orm/tiny/model.hpp>

#include "../Defines.h"

namespace Models {

using Orm::Tiny::Model;
using Orm::Tiny::Relations::Pivot;

// NOLINTNEXTLINE(misc-no-recursion)
class Role;

class User final : public Model<User, Role, Pivot> {
   friend Model;
   using Model::Model;

 public:
   /*! The roles that belong to the user. */
   std::unique_ptr<BelongsToMany<User, Role>>
   roles() {
      return belongsToMany<Role>();
   }

 private:
   /*! Map of relation names to methods. */
   QHash<QString, RelationVisitor> u_relations{
       {"roles", [](auto& v) { v(&User::roles); }},
   };
};

class Role final : public Model<Role, User, Pivot> {
   friend Model;
   using Model::Model;

 public:
   /*! The users that belong to the role. */
   std::unique_ptr<BelongsToMany<Role, User>>
   users() {
      return belongsToMany<User>();
   }

 private:
   /*! Map of relation names to methods. */
   QHash<QString, RelationVisitor> u_relations{
       {"users", [](auto& v) { v(&Role::users); }},
   };
};
}  // namespace Models

#endif  // MODELS_USER_HPP
```

**Comment by Redmanacac** [comment]
I just added the missing include, and the error persist.

If I do this, it compiles
```
class User final : public Model<User, Role, Pivot> {
   friend Model;
   using Model::Model;

 public:
   // /*! The roles that belong to the user. */
   // std::unique_ptr<BelongsToMany<User, Role>>
   // roles() {
   //    return belongsToMany<Role>();
   // }

 private:
   // /*! Map of relation names to methods. */
   // QHash<QString, RelationVisitor> u_relations{
   //     {"roles", [](auto& v) { v(&User::roles); }},
   // };
};
```

**Comment by silverqx** [comment]
For me it compiles on msvc, can you post the rest of your code?

**Comment by Redmanacac** [comment]
Compiler: Microsoft Visual C++ Compiler 17.7.34024.191 (amd64)

There is no other code to the models except the one I posted.

What else could be of relevance to that?

**Comment by silverqx** [comment]
Paste a whole file here I try to compile it on my side.

**Comment by silverqx** [comment]
> What else could be of relevance to that?

I don't know code looks correct, maybe its in build system, pack whole folder with source and build system and I try it to recompile if I find something.

**Comment by Redmanacac** [comment]
Ah, well. Mutually including the headers of the other table breaks it. Moved it all into one file and now it compiles.
