### ISSUE TITLE
When will the sqlite database be supported?

### ISSUE THREAD

**Issue by faywong** [silverqx/TinyORM#50]
Thx for your great work. I am wondering when will the sqlite database be supported?

**Comment by silverqx** [comment]
The SQLite database is fully supported [docs](https://www.tinyorm.org/database/getting-started#introduction).

**Comment by silverqx** [comment]
Why do you think or how did you find out that it's not supported?

**Comment by silverqx** [comment]
This is only true for our own TinyDrivers you can still use QtSql database drivers, with QtSql drivers all 3 (or 4 databases with MariaDB) are supported, I will have to somehow update these docs because it can be confusing.

Thx for pointing it out.

**Comment by silverqx** [comment]
I have updated this [Features Summary](https://github.com/silverqx/TinyORM?tab=readme-ov-file#summary-list) to be less confusing, also added the Tip Admonitions at the [`TinyDrivers`](https://www.tinyorm.org/tinydrivers/getting-started) docs page.
