### ISSUE TITLE
Table::find and cascaded relations fetching

### ISSUE THREAD

**Issue by edubois** [silverqx/TinyORM#53]
Hi,

Assuming I have this hierarchy of classes:

```cpp
struct TableParent : public Model<TableParent, TableChildL0>
{

std::unique_ptr<Orm::Tiny::Relations::HasMany<TableParent, TableChildL0>> childrenL0()
{
    return hasMany<TableChildL0>();
}
};

struct TableChildL0 : public Model<TableChildL0, TableChildL1>
{
std::unique_ptr<Orm::Tiny::Relations::BelongsTo<TableChildL0, TableParent>> childL0Parent()
{
    return belongsTo<TableParent>("table_parent_parent_id", "parent_id");
}
std::unique_ptr<Orm::Tiny::Relations::HasMany<TableChildL0, TableChildL1>> childrenL1()
{
    return hasMany<TableChildL1>();
}
};

struct TableChildL1 : public Model<TableChildL1>
{
std::unique_ptr<Orm::Tiny::Relations::BelongsTo<TableChildL1, TableChildL0>> childL1Parent()
{
    return belongsTo<TableChildL0>("table_parent_l0_l0_id", "l0_id");
}
};
```

How can I do a `TableParent::find(ID)` so that I get all relations pulled into their respective objects?
Right now, it works with only 1 level:
```cpp
auto toplevel = TableParent::find(ID); // Works fine, I get the parent
auto l0Children = toplevel->getRelationValue<TableChildL0>("listChildrenL0"); // Works fine, I get L0 children
auto l1Children = l0Children->getRelationValue<TableChildL1>("listChildrenL1"); // Does not work, for some reason the relation is not filled even though there are L1 records `associated` with L0
```

**Comment by silverqx** [comment]
You can use [Nested Eager Loading](https://www.tinyorm.org/tinyorm/relationships#nested-eager-loading) or [Lazy Eager Loading](https://www.tinyorm.org/tinyorm/relationships#lazy-eager-loading) and use **dot notation** like `"listChildrenL0.listChildrenL1"`. Also look at [Relationship Methods](https://www.tinyorm.org/tinyorm/relationships#relationship-methods). I would recommend to read the [TinyORM: Relationships](https://www.tinyorm.org/tinyorm/relationships) documentation as everything is already described there.

I think something like this could work:
```cpp
auto toplevel = TableParent::find(ID);
auto l0Children = toplevel->getRelationValue<TableChildL0>("listChildrenL0");

for (auto *l0 : l0Children)
    auto *l1Children = l0->getRelationValue<TableChildL1>("listChildrenL1");
```

or hydrate eagerly at once:
```cpp
auto toplevel = TableParent::with("listChildrenL0.listChildrenL1")->find(ID);
```

You can also call `load()` with **dot notation** to lazy load:
```cpp
auto toplevel = TableParent::find(ID);
toplevel.load("listChildrenL0.listChildrenL1");
```

The `getRelationValue()` lazy loads the relation if the relationship isn't loaded, so you don't need to call `load()` explicitly, there is also the `getRelation()` that doesn't do this.

I haven't tested the code above so there is a chance it will not work.

**Comment by silverqx** [comment]
Did you figure out how it works? Do you need help with it?

**Comment by edubois** [comment]
Yes, thanks for your answer!
