### ISSUE TITLE
Polymorphic inheritance loading

### ISSUE THREAD

**Issue by edubois** [silverqx/TinyORM#54]
Hi,

Assuming I have a base class `IVehicule` and I have `Car` inheriting from `IVehicule`. Let's say I have a table `User` referencing a relation one-to-many to `IVehicule` and I inserted an `Car` as child to `User`. How can I `load` all `IVehicule` relation objects even if they actually are `Car`?

Do I have to make multiple relations for each derived types (`User::listCars`, `User::listTrucks`, ....)? or is there a more elegant way using the base class `IVehicule`?

Thanks!

**Comment by silverqx** [comment]
No Inheritance mapping or polymorphic relations are not supported, I never used these types of relations and don't plan to add support for them in the near future.
